### ISSUE TITLE
Didn't get the exe file inside the zip file

### ISSUE THREAD

**Issue by kcvinker** [hernandp/MessageCrackerWizard#2]
Hi,
I didn't get the exe file inside the zip file. Is it missed ?

**Comment by hernandp** [comment]
ZIP is source code only.  Binary is provided here 
https://github.com/hernandp/MessageCrackerWizard/releases/download/2.2/MessageCrackWiz.exe

**Comment by kcvinker** [comment]
Thanks. Got it. :)
