### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by bugiii** [hernandp/MessageCrackerWizard#3]
A memory error occurs due to a string length problem referring to the wrong control handle.

IDC_HANDLEMSG should be used rather than IDC_MSGFUNCTION, and hwnd of Edit_LineIndex.

https://github.com/hernandp/MessageCrackerWizard/blob/77a57ce6b085d79ab0cf9620f680f9c406c50d64/Clipboard.cpp#L71

https://github.com/hernandp/MessageCrackerWizard/blob/77a57ce6b085d79ab0cf9620f680f9c406c50d64/Clipboard.cpp#L104-L105

**Comment by hernandp** [comment]
Nice catch.

**Comment by hernandp** [comment]
Already fixed.
