### ISSUE TITLE
How do i use this ? There is no "exe" file

### ISSUE THREAD

**Issue by kcvinker** [hernandp/MessageCrackerWizard#5]
Hi, I just downloaded the folder. But sadly, i cant find any exe file in this folder. Do i need to compile this ? If so, what are the prerequisites ?

**Comment by hernandp** [comment]
1) Go to Releases and download the 2.5 executable https://github.com/hernandp/MessageCrackerWizard/releases/download/v2.5/MessageCrackWiz.exe

2) Use the Solution file to open it in Visual Studio IDE.  If you don't have VS available you can still compile it using MSBUILD by downloading the Build Tools only.

**Comment by kcvinker** [comment]
@hernandp ,
Thank a lot. Well, i am playing with some win api code in Nim. So this tool will help me to code in Nim also. However, i am planning to make some event style in Nim like vb.net. :)
